name: Pack core

on:
  push:
    paths:
      - solutions/**
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: out/core.zip
          solution-folder: solutions
          solution-type: Both
      - uses: actions/upload-artifact@v2
        with:
          name: packed-solution
          path: out/